# Generated by Django 5.2.3 on 2025-06-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_animal_propietario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='nombre',
            new_name='nombre_animal',
        ),
    ]
